let careerList = [{
    img: "https://images.pexels.com/photos/3861959/pexels-photo-3861959.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
    link: "https://docs.google.com/document/d/1C8ZvdjPRMM-Zpp4_bpBQx6_QJJqfYm3iyMyfQ8aJZ2U/edit?usp=sharing",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis magnam ut libero corporis esse qui sapiente nam exercitationem dicta error natus porro doloribus, atque placeat voluptate voluptates architecto, tempore consectetur, facere totam hic! Voluptate fugit magni placeat quaerat quis impedit! Quasi ullam omnis delectus adipisci odio porro nobis voluptatem est dignissimos accusantium provident aperiam eligendi temporibus veritatis deleniti, earum saepe dolor neque, amet, aliquid nihil vitae debitis? Nemo quas voluptate illo voluptates. Earum a recusandae facilis saepe quia soluta, cum inventore blanditiis quae minima rem doloremque vero! Quod, quasi? Recusandae dignissimos quam nulla quisquam aliquid, natus ipsam doloremque animi itaque ipsum eligendi. Architecto, delectus. Quo delectus rerum cum neque assumenda consequatur dicta voluptatibus? Quidem officia consequuntur accusantium eos debitis aliquam quam nostrum consectetur eum nam similique nulla praesentium, suscipit corrupti dolorem repudiandae voluptas impedit qui velit ab aut totam numquam! Quos sapiente accusantium blanditiis a consequatur sequi? Tenetur expedita dolores ullam asperiores ad sequi animi quidem quod maiores, minus earum velit, quasi amet cumque! Neque rem quo at temporibus excepturi. Eaque, sunt culpa? Dignissimos, odio. Quaerat quas dolorum quidem voluptate aliquam assumenda ad repudiandae necessitatibus rem, quibusdam, vitae magnam facilis, corrupti dolorem. Provident, iusto quidem modi mollitia adipisci aspernatur repellendus.",
    title: "SOFTWARE DEVELOPMENT"
}, {
    img: "https://images.pexels.com/photos/6366444/pexels-photo-6366444.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    link: "https://docs.google.com/document/d/1C8ZvdjPRMM-Zpp4_bpBQx6_QJJqfYm3iyMyfQ8aJZ2U/edit?usp=sharing",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis magnam ut libero corporis esse qui sapiente nam exercitationem dicta error natus porro doloribus, atque placeat voluptate voluptates architecto, tempore consectetur, facere totam hic! Voluptate fugit magni placeat quaerat quis impedit! Quasi ullam omnis delectus adipisci odio porro nobis voluptatem est dignissimos accusantium provident aperiam eligendi temporibus veritatis deleniti, earum saepe dolor neque, amet, aliquid nihil vitae debitis? Nemo quas voluptate illo voluptates. Earum a recusandae facilis saepe quia soluta, cum inventore blanditiis quae minima rem doloremque vero! Quod, quasi? Recusandae dignissimos quam nulla quisquam aliquid, natus ipsam doloremque animi itaque ipsum eligendi. Architecto, delectus. Quo delectus rerum cum neque assumenda consequatur dicta voluptatibus? Quidem officia consequuntur accusantium eos debitis aliquam quam nostrum consectetur eum nam similique nulla praesentium, suscipit corrupti dolorem repudiandae voluptas impedit qui velit ab aut totam numquam! Quos sapiente accusantium blanditiis a consequatur sequi? Tenetur expedita dolores ullam asperiores ad sequi animi quidem quod maiores, minus earum velit, quasi amet cumque! Neque rem quo at temporibus excepturi. Eaque, sunt culpa? Dignissimos, odio. Quaerat quas dolorum quidem voluptate aliquam assumenda ad repudiandae necessitatibus rem, quibusdam, vitae magnam facilis, corrupti dolorem. Provident, iusto quidem modi mollitia adipisci aspernatur repellendus.",
    title: "QUANT"
}, {
    img: "https://images.pexels.com/photos/288477/pexels-photo-288477.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
    link: "https://docs.google.com/document/d/1C8ZvdjPRMM-Zpp4_bpBQx6_QJJqfYm3iyMyfQ8aJZ2U/edit?usp=sharing",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis magnam ut libero corporis esse qui sapiente nam exercitationem dicta error natus porro doloribus, atque placeat voluptate voluptates architecto, tempore consectetur, facere totam hic! Voluptate fugit magni placeat quaerat quis impedit! Quasi ullam omnis delectus adipisci odio porro nobis voluptatem est dignissimos accusantium provident aperiam eligendi temporibus veritatis deleniti, earum saepe dolor neque, amet, aliquid nihil vitae debitis? Nemo quas voluptate illo voluptates. Earum a recusandae facilis saepe quia soluta, cum inventore blanditiis quae minima rem doloremque vero! Quod, quasi? Recusandae dignissimos quam nulla quisquam aliquid, natus ipsam doloremque animi itaque ipsum eligendi. Architecto, delectus. Quo delectus rerum cum neque assumenda consequatur dicta voluptatibus? Quidem officia consequuntur accusantium eos debitis aliquam quam nostrum consectetur eum nam similique nulla praesentium, suscipit corrupti dolorem repudiandae voluptas impedit qui velit ab aut totam numquam! Quos sapiente accusantium blanditiis a consequatur sequi? Tenetur expedita dolores ullam asperiores ad sequi animi quidem quod maiores, minus earum velit, quasi amet cumque! Neque rem quo at temporibus excepturi. Eaque, sunt culpa? Dignissimos, odio. Quaerat quas dolorum quidem voluptate aliquam assumenda ad repudiandae necessitatibus rem, quibusdam, vitae magnam facilis, corrupti dolorem. Provident, iusto quidem modi mollitia adipisci aspernatur repellendus.",
    title: "CONSULTING"
}, {
    img: "https://images.pexels.com/photos/53621/calculator-calculation-insurance-finance-53621.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
    link: "https://docs.google.com/document/d/1C8ZvdjPRMM-Zpp4_bpBQx6_QJJqfYm3iyMyfQ8aJZ2U/edit?usp=sharing",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis magnam ut libero corporis esse qui sapiente nam exercitationem dicta error natus porro doloribus, atque placeat voluptate voluptates architecto, tempore consectetur, facere totam hic! Voluptate fugit magni placeat quaerat quis impedit! Quasi ullam omnis delectus adipisci odio porro nobis voluptatem est dignissimos accusantium provident aperiam eligendi temporibus veritatis deleniti, earum saepe dolor neque, amet, aliquid nihil vitae debitis? Nemo quas voluptate illo voluptates. Earum a recusandae facilis saepe quia soluta, cum inventore blanditiis quae minima rem doloremque vero! Quod, quasi? Recusandae dignissimos quam nulla quisquam aliquid, natus ipsam doloremque animi itaque ipsum eligendi. Architecto, delectus. Quo delectus rerum cum neque assumenda consequatur dicta voluptatibus? Quidem officia consequuntur accusantium eos debitis aliquam quam nostrum consectetur eum nam similique nulla praesentium, suscipit corrupti dolorem repudiandae voluptas impedit qui velit ab aut totam numquam! Quos sapiente accusantium blanditiis a consequatur sequi? Tenetur expedita dolores ullam asperiores ad sequi animi quidem quod maiores, minus earum velit, quasi amet cumque! Neque rem quo at temporibus excepturi. Eaque, sunt culpa? Dignissimos, odio. Quaerat quas dolorum quidem voluptate aliquam assumenda ad repudiandae necessitatibus rem, quibusdam, vitae magnam facilis, corrupti dolorem. Provident, iusto quidem modi mollitia adipisci aspernatur repellendus.",
    title: "FINANACE"
}, {
    img: "https://images.pexels.com/photos/10347136/pexels-photo-10347136.jpeg?cs=srgb&dl=pexels-ron-lach-10347136.jpg&fm=jpg",
    link: "https://docs.google.com/document/d/1C8ZvdjPRMM-Zpp4_bpBQx6_QJJqfYm3iyMyfQ8aJZ2U/edit?usp=sharing",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis magnam ut libero corporis esse qui sapiente nam exercitationem dicta error natus porro doloribus, atque placeat voluptate voluptates architecto, tempore consectetur, facere totam hic! Voluptate fugit magni placeat quaerat quis impedit! Quasi ullam omnis delectus adipisci odio porro nobis voluptatem est dignissimos accusantium provident aperiam eligendi temporibus veritatis deleniti, earum saepe dolor neque, amet, aliquid nihil vitae debitis? Nemo quas voluptate illo voluptates. Earum a recusandae facilis saepe quia soluta, cum inventore blanditiis quae minima rem doloremque vero! Quod, quasi? Recusandae dignissimos quam nulla quisquam aliquid, natus ipsam doloremque animi itaque ipsum eligendi. Architecto, delectus. Quo delectus rerum cum neque assumenda consequatur dicta voluptatibus? Quidem officia consequuntur accusantium eos debitis aliquam quam nostrum consectetur eum nam similique nulla praesentium, suscipit corrupti dolorem repudiandae voluptas impedit qui velit ab aut totam numquam! Quos sapiente accusantium blanditiis a consequatur sequi? Tenetur expedita dolores ullam asperiores ad sequi animi quidem quod maiores, minus earum velit, quasi amet cumque! Neque rem quo at temporibus excepturi. Eaque, sunt culpa? Dignissimos, odio. Quaerat quas dolorum quidem voluptate aliquam assumenda ad repudiandae necessitatibus rem, quibusdam, vitae magnam facilis, corrupti dolorem. Provident, iusto quidem modi mollitia adipisci aspernatur repellendus.",
    title: "CORE"
}, {
    img: "https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
    link: "https://docs.google.com/document/d/1C8ZvdjPRMM-Zpp4_bpBQx6_QJJqfYm3iyMyfQ8aJZ2U/edit?usp=sharing",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis magnam ut libero corporis esse qui sapiente nam exercitationem dicta error natus porro doloribus, atque placeat voluptate voluptates architecto, tempore consectetur, facere totam hic! Voluptate fugit magni placeat quaerat quis impedit! Quasi ullam omnis delectus adipisci odio porro nobis voluptatem est dignissimos accusantium provident aperiam eligendi temporibus veritatis deleniti, earum saepe dolor neque, amet, aliquid nihil vitae debitis? Nemo quas voluptate illo voluptates. Earum a recusandae facilis saepe quia soluta, cum inventore blanditiis quae minima rem doloremque vero! Quod, quasi? Recusandae dignissimos quam nulla quisquam aliquid, natus ipsam doloremque animi itaque ipsum eligendi. Architecto, delectus. Quo delectus rerum cum neque assumenda consequatur dicta voluptatibus? Quidem officia consequuntur accusantium eos debitis aliquam quam nostrum consectetur eum nam similique nulla praesentium, suscipit corrupti dolorem repudiandae voluptas impedit qui velit ab aut totam numquam! Quos sapiente accusantium blanditiis a consequatur sequi? Tenetur expedita dolores ullam asperiores ad sequi animi quidem quod maiores, minus earum velit, quasi amet cumque! Neque rem quo at temporibus excepturi. Eaque, sunt culpa? Dignissimos, odio. Quaerat quas dolorum quidem voluptate aliquam assumenda ad repudiandae necessitatibus rem, quibusdam, vitae magnam facilis, corrupti dolorem. Provident, iusto quidem modi mollitia adipisci aspernatur repellendus.",
    title: "ARTIFICIAL INTELLIGENCE"
}, {
    img: "https://images.pexels.com/photos/10347136/pexels-photo-10347136.jpeg?cs=srgb&dl=pexels-ron-lach-10347136.jpg&fm=jpg",
    link: "https://docs.google.com/document/d/1C8ZvdjPRMM-Zpp4_bpBQx6_QJJqfYm3iyMyfQ8aJZ2U/edit?usp=sharing",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis magnam ut libero corporis esse qui sapiente nam exercitationem dicta error natus porro doloribus, atque placeat voluptate voluptates architecto, tempore consectetur, facere totam hic! Voluptate fugit magni placeat quaerat quis impedit! Quasi ullam omnis delectus adipisci odio porro nobis voluptatem est dignissimos accusantium provident aperiam eligendi temporibus veritatis deleniti, earum saepe dolor neque, amet, aliquid nihil vitae debitis? Nemo quas voluptate illo voluptates. Earum a recusandae facilis saepe quia soluta, cum inventore blanditiis quae minima rem doloremque vero! Quod, quasi? Recusandae dignissimos quam nulla quisquam aliquid, natus ipsam doloremque animi itaque ipsum eligendi. Architecto, delectus. Quo delectus rerum cum neque assumenda consequatur dicta voluptatibus? Quidem officia consequuntur accusantium eos debitis aliquam quam nostrum consectetur eum nam similique nulla praesentium, suscipit corrupti dolorem repudiandae voluptas impedit qui velit ab aut totam numquam! Quos sapiente accusantium blanditiis a consequatur sequi? Tenetur expedita dolores ullam asperiores ad sequi animi quidem quod maiores, minus earum velit, quasi amet cumque! Neque rem quo at temporibus excepturi. Eaque, sunt culpa? Dignissimos, odio. Quaerat quas dolorum quidem voluptate aliquam assumenda ad repudiandae necessitatibus rem, quibusdam, vitae magnam facilis, corrupti dolorem. Provident, iusto quidem modi mollitia adipisci aspernatur repellendus.",
    title: "MACHINE LEARNING"
},]

export default careerList;